/**
 * KoinWork Database Types
 * Mirrors the Supabase PostgreSQL schema.
 * Update this file when running `supabase gen types typescript`.
 */

export type UserRole = "owner" | "employee";
export type KycStatus = "NOT_SUBMITTED" | "PENDING" | "APPROVED" | "REJECTED";
export type TransactionType =
  | "DEPOSIT"
  | "ESCROW_FREEZE"
  | "ESCROW_RELEASE"
  | "PAYMENT"
  | "WITHDRAWAL"
  | "REFUND"
  | "BOOST_FEE";
export type TransactionStatus = "PENDING" | "COMPLETED" | "FAILED" | "REVERSED";
export type CampaignStatus =
  | "DRAFT"
  | "OPEN"
  | "IN_PROGRESS"
  | "SETTLING"
  | "SETTLED"
  | "CANCELLED";
export type EscrowStatus =
  | "NONE"
  | "FROZEN"
  | "PARTIAL_RELEASE"
  | "SETTLED"
  | "REFUNDED";
export type SlotStatus =
  | "AVAILABLE"
  | "APPLIED"
  | "ASSIGNED"
  | "COMPLETED"
  | "NO_SHOW"
  | "DISPUTED"
  | "CANCELLED";
export type ApplicationStatus = "PENDING" | "ACCEPTED" | "REJECTED" | "WITHDRAWN";
export type WithdrawalStatus =
  | "PENDING"
  | "PROCESSING"
  | "COMPLETED"
  | "FAILED"
  | "CANCELLED";
export type DisputeStatus =
  | "OPEN"
  | "UNDER_REVIEW"
  | "RESOLVED_OWNER"
  | "RESOLVED_EMPLOYEE"
  | "CLOSED";
export type BoostTier = "BASIC" | "STANDARD" | "PREMIUM";
export type NotificationType =
  | "APPLICATION_RECEIVED"
  | "APPLICATION_ACCEPTED"
  | "APPLICATION_REJECTED"
  | "WORK_APPROVED"
  | "PAYMENT_RECEIVED"
  | "WITHDRAWAL_PROCESSED"
  | "DISPUTE_UPDATE"
  | "CAMPAIGN_UPDATE"
  | "SYSTEM";

// ─── Row types ───────────────────────────────────────────────────────────────

export interface Profile {
  id: string;
  role: UserRole;
  full_name: string;
  phone: string | null;
  avatar_url: string | null;
  bio: string | null;
  location: unknown | null; // PostGIS geography — raw value from DB
  city: string | null;
  state: string | null;
  location_updated_at: string;
  kyc_status: KycStatus;
  kyc_verified_at: string | null;
  avg_rating: number;
  total_reviews: number;
  is_active: boolean;
  created_at: string;
  updated_at: string;
}

export interface Wallet {
  id: string;
  user_id: string;
  /** Integer paisa. 1 KCoin = 1000 paisa */
  available_balance: number;
  /** Integer paisa. Amount frozen (e.g. pending withdrawal or escrow) */
  frozen_balance: number;
  /** Integer paisa. Total ever earned */
  lifetime_earned: number;
  /** Integer paisa. Total ever spent */
  lifetime_spent: number;
  created_at: string;
  updated_at: string;
}

export interface Transaction {
  id: string;
  wallet_id: string;
  /** Integer paisa. Positive = credit, negative = debit */
  amount_paisa: number;
  type: TransactionType;
  status: TransactionStatus;
  idempotency_key: string;
  reference_id: string | null;
  reference_type: string | null;
  description: string | null;
  metadata: Record<string, unknown>;
  created_at: string;
  updated_at: string;
}

// ─── Database helper type (for createClient generic) ─────────────────────────
// Matches the structure generated by `supabase gen types typescript`

export interface Database {
  public: {
    Tables: {
      profiles: {
        Row: Profile;
        Insert: {
          id: string;
          role: UserRole;
          full_name: string;
          phone?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          location?: unknown | null;
          city?: string | null;
          state?: string | null;
          location_updated_at?: string;
          kyc_status?: KycStatus;
          kyc_verified_at?: string | null;
          avg_rating?: number;
          total_reviews?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          role?: UserRole;
          full_name?: string;
          phone?: string | null;
          avatar_url?: string | null;
          bio?: string | null;
          location?: unknown | null;
          city?: string | null;
          state?: string | null;
          location_updated_at?: string;
          kyc_status?: KycStatus;
          kyc_verified_at?: string | null;
          avg_rating?: number;
          total_reviews?: number;
          is_active?: boolean;
          updated_at?: string;
        };
        Relationships: [];
      };
      wallets: {
        Row: Wallet;
        Insert: {
          id?: string;
          user_id: string;
          available_balance?: number;
          frozen_balance?: number;
          lifetime_earned?: number;
          lifetime_spent?: number;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          user_id?: string;
          available_balance?: number;
          frozen_balance?: number;
          lifetime_earned?: number;
          lifetime_spent?: number;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "wallets_user_id_fkey";
            columns: ["user_id"];
            isOneToOne: true;
            referencedRelation: "profiles";
            referencedColumns: ["id"];
          }
        ];
      };
      transactions: {
        Row: Transaction;
        Insert: {
          id?: string;
          wallet_id: string;
          amount_paisa: number;
          type: TransactionType;
          status?: TransactionStatus;
          idempotency_key: string;
          reference_id?: string | null;
          reference_type?: string | null;
          description?: string | null;
          metadata?: Record<string, unknown>;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          wallet_id?: string;
          amount_paisa?: number;
          type?: TransactionType;
          status?: TransactionStatus;
          idempotency_key?: string;
          reference_id?: string | null;
          reference_type?: string | null;
          description?: string | null;
          metadata?: Record<string, unknown>;
          updated_at?: string;
        };
        Relationships: [
          {
            foreignKeyName: "transactions_wallet_id_fkey";
            columns: ["wallet_id"];
            isOneToOne: false;
            referencedRelation: "wallets";
            referencedColumns: ["id"];
          }
        ];
      };
    };
    Views: Record<string, never>;
    Functions: Record<string, never>;
    Enums: {
      user_role: UserRole;
      kyc_status: KycStatus;
      transaction_type: TransactionType;
      transaction_status: TransactionStatus;
    };
    CompositeTypes: Record<string, never>;
  };
}
